### ISSUE TITLE
Config_patch not working

### ISSUE THREAD

**Issue by paucampana** [tensor5/terraform-provider-talos#158]
Hi there,

I am trying to use `config_patch` but it is not working..or I am using it wrong. There are no examples of how to use it. I would like to do the same I did with `talos gen config` command: 
`--config-patch '[{"op": "replace", "path": "/cluster/allowSchedulingOnMasters", "value": true}]'`

But I did not find how I should do it with this terraform module. Not sure if it is working.

```
resource "talos_gen_config" "config" {
  cluster_name     = "test-talos-tf"
  cluster_endpoint = "https://test:443"
  kubernetes_version = "1.23.9"
  config_patch = ["{op: replace, path: /cluster/allowSchedulingOnMasters, value: true}"]
  talos_version = "v1.2"
}

output "control_plane_config" {
  value = talos_gen_config.config.control_plane_config `allowSchedulingOnMasters`
}
```

Checking the output I see that `allowSchedulingOnMasters` config does not appear. How I should use config_patch?

### Terraform Version
```
terraform -v
Terraform v1.2.6
```

### Affected Resource(s)
- talos_gen_config

### Expected Behavior

`allowSchedulingOnMasters: true` should appear in the control plane config

### Actual Behavior
`allowSchedulingOnMasters: true` does not appear in the control plane config

**Comment by tensor5** [comment]
Hi @paucampana, it seems there is a problem with the `config_patch` parameter of the `talos_gen_config` resource, I'll try to fix it ASAP.

**Comment by tensor5** [comment]
Hi @paucampana, try with:

```hcl
resource "talos_gen_config" "config" {
  cluster_name     = "test-talos-tf"
  cluster_endpoint = "https://test:443"
  kubernetes_version = "1.23.9"
  config_patch = ["[{\"op\": \"add\", \"path\": \"/cluster/allowSchedulingOnMasters\", \"value\": true}]"]
  talos_version = "v1.2"
}
```

(notice the extra pair of square brackets that makes the JSON into an array).  It's not the best syntax, so I'm planning to replace the JSON string with a native HCL object in the next release.

**Comment by paucampana** [comment]
thanks!!
